const{Schema, model}=require('mongoose');


const succesSchema = new Schema({
    gen1:{
        rousse:{
            type:Boolean,
            default:false,
        },
        amande:{
            type:Boolean,
            default:false,
        },
        doree:{
            type:Boolean,
            default:false,
        }
    },
    gen2:{
        rousseAmande:{
            type:Boolean,
            default:false,
        },
        rousseDoree:{
            type:Boolean,
            default:false,
        },
        AmandeDoree:{
            type:Boolean,
            default:false,
        }
    },
    gen3:{
        indigo:{
            type:Boolean,
            default:false,
        },
        Ebene:{
            type:Boolean,
            default:false,
        }
    },
    gen4:{
        rousseIndigo:{
            type:Boolean,
            default:false,
        },
        rousseEbene:{
            type:Boolean,
            default:false,
        },
        amandeIndigo:{
            type:Boolean,
            default:false,
        },
        amandeEbene:{
            type:Boolean,
            default:false,
        },
        doreeIndigo:{
            type:Boolean,
            default:false,
        },
        doreeEbene:{
            type:Boolean,
            default:false,
        },
        indigoEbene:{
            type:Boolean,
            default:false,
        }
    },
    gen5:{
        pourpre:{
            type:Boolean,
            default:false,
        },
        orchidee:{
            type:Boolean,
            default:false,
        }
    },
    gen6:{
        roussePourpre:{
            type:Boolean,
            default:false,
        },
        rousseOrchidee:{
            type:Boolean,
            default:false,
        },
        amandePourpre:{
            type:Boolean,
            default:false,
        },
        amandeOrchidee:{
            type:Boolean,
            default:false,
        },
        doreePoupre:{
            type:Boolean,
            default:false,
        },
        doreeOrchidee:{
            type:Boolean,
            default:false,
        },
        indigoPourpre:{
            type:Boolean,
            default:false,
        },
        indigoOrchidee:{
            type:Boolean,
            default:false,
        },
        ebenePourpre:{
            type:Boolean,
            default:false,
        },
        ebeneOrchidee:{
            type:Boolean,
            default:false,
        },
        pourpeOrchidee:{
            type:Boolean,
            default:false,
        }
    },
    gen7:{
        ivoire:{
            type:Boolean,
            default:false,
        },
        turquoise:{
            type:Boolean,
            default:false,
        }
    },
    gen8:{
        rousseIvoire:{
            type:Boolean,
            default:false,
        },
        rousseTurquoise:{
            type:Boolean,
            default:false,
        },
        amandeIvoire:{
            type:Boolean,
            default:false,
        },
        amandeTurquoise:{
            type:Boolean,
            default:false,
        },
        doreeIvoire:{
            type:Boolean,
            default:false,
        },
        doreeTurquoise:{
            type:Boolean,
            default:false,
        },
        indigoIvoire:{
            type:Boolean,
            default:false,
        },
        indigoTurquoise:{
            type:Boolean,
            default:false,
        },
        ebeneIvoire:{
            type:Boolean,
            default:false,
        },
        ebeneTurquoise:{
            type:Boolean,
            default:false,
        },
        pourpreIvoire:{
            type:Boolean,
            default:false,
        },
        pourpreTurquoise:{
            type:Boolean,
            default:false,
        },
        orchideeIvoire:{
            type:Boolean,
            default:false,
        },
        orchideeTurquoise:{
            type:Boolean,
            default:false,
        },
        ivoireTurquoise:{
            type:Boolean,
            default:false,
        }
    },
    gen9:{
        emeraude:{
            type:Boolean,
            default:false,
        },
        prune:{
            type:Boolean,
            default:false,
        }
    },
    gen10:{
        rousseEmeraude:{
            type:Boolean,
            default:false,
        },
        roussePrune:{
            type:Boolean,
            default:false,
        },
        amandeEmeraude:{
            type:Boolean,
            default:false,
        },
        amandePrune:{
            type:Boolean,
            default:false,
        },
        doreeEmeraude:{
            type:Boolean,
            default:false,
        },
        doreePrune:{
            type:Boolean,
            default:false,
        },
        indigoEmeraude:{
            type:Boolean,
            default:false,
        },
        indigoPrune:{
            type:Boolean,
            default:false,
        },
        ebeneEmeraude:{
            type:Boolean,
            default:false,
        },
        ebenePrune:{
            type:Boolean,
            default:false,
        },
        pourpreEmeraude:{
            type:Boolean,
            default:false,
        },
        pourprePrune:{
            type:Boolean,
            default:false,
        },
        orchideeEmeraude:{
            type:Boolean,
            default:false,
        },
        orchideePrune:{
            type:Boolean,
            default:false,
        },
        ivoireEmeraude:{
            type:Boolean,
            default:false,
        },
        ivoirePrune:{
            type:Boolean,
            default:false,
        },
        turquoiseEmeraude:{
            type:Boolean,
            default:false,
        },
        turquoisePrune:{
            type:Boolean,
            default:false,
        },
        emeraudePrune:{
            type:Boolean,
            default:false,
        },

    }
},{
    collection:'Succes',
    timestamp:true
})

const Succes= model('Succes',succesSchema);

module.exports= Succes;